apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  name: broker
spec:
  deploymentPlan:
    size: 1
    image: registry.redhat.io/amq7/amq-broker:7.8
  acceptors:
    - name: artemis_acceptor
      protocols: core,openwire
      port: 61616
      sslEnabled: false
    - name: amqp_acceptor
      protocols: amqp
      port: 5672
      sslEnabled: false